version: '2.4'
services:
  backend:
    container_name: backend
    image: sidoux/tp-api
    networks:
      - network
    depends_on:
      - database

  database:
    container_name: database
    image: sidoux/tp-db
    networks:
      - network

  httpd:
    container_name: httpd
    image: sidoux/tp-http
    ports:
      - "80:80"
    networks:
      - network
    depends_on:
      - backend

networks:
  network:
